### ISSUE TITLE
node modules should not be commited to Github

### ISSUE THREAD

**Issue by ndsvw** [MohamedYasser97/RoboTwit#1]
You uploaded the folder "node_modules" and wrote in your Readme:

> If you face any problems on platforms other than Windows, I advise that you delete the node_modules directory and install the following packages:

That's unnecessary because the information which packages the user needs are stored in the package.json file.

The user just needs to run "npm install" and automaticly loads and installs all the repositories. This does also work on other operating systems.

You could just remove the "node_modules" folder and create a ".gitignore" file with the content "node_modules" so that they'll not be pushed to github.

**Comment by yasserror** [comment]
I thought of exactly the same thing but I wasn't sure of what the "best practice" is as I'm kind of new to Node.js so I came across this answer on SO:

https://stackoverflow.com/questions/18128863/should-node-modules-folder-be-included-in-the-git-repository/36296320

I know that I won't be able to maintain this project for long and I'd like it to be intact for the most time possible so I kept the "node_modules" folder.

Thanks for the advice though.
